#!/usr/bin/env bash
#Transfers file from client to server
# The IP of the server we want to transer the file to
# Display a message if less than 3 parameters passed
# Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]
then
      echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    path_to_file=$1
    ip=$2
    username=$3
    path_to_ssh_key=$4
    ssh_key_path=$4
    scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$path_to_file" "$username@$ip":~
fi