#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx restart
