#!/usr/bin/env bash

# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
STRING="Hello World!"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
FILE="/etc/nginx/sites-available/default"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "$STRING" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i "37i\ $REDIRECT" "$FILE"
sudo service nginx restart
