#!/usr/bin/env bash
#Solving thew FizzBuzz problem using shell

i="1"
while [ "$i" -le 100 ]; do
        if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
             echo "FizzBuzz"
        elif [ $((i % 3)) -eq 0 ]; then
               echo "Fizz"
        elif  [ $((i % 5)) -eq 0 ]; then
                echo "Buzz"
        else
            echo "$i"
        fi;

        i=$((i + 1))
done