#!/usr/bin/env bash
# Printss out a "Best School" and on 9th Line prints out "Hello"

i="1"
while [ "$i" -le 10 ]; do
         echo "Best School"
         if [ "$i" -eq 9 ]; then
               echo "Hi"
          fi;
          i=$((i + 1))
done;
